resources:
  - name: sample_python
    type: gitRepo
    repoPath: ric03uec/sample_python
    configuration:
      integrationName: ric03uec-github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_1
    setup:
      runtime: host
    steps:
      - name: test_bash_step
        type: bash
        configuration:
          affinityGroup: test_affinity_group
        setup:
          runtime: host
        triggeredBy:
          resources:
            - sample_python 
        execution:
          onExecute:
            - echo "First run....."
            - echo "executing step_A..."
